version: "3.1"

services:
    db:
        image: postgres:15
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            - odoo-db:/var/lib/postgresql/data

    odoo:
        image: odoo:17
        depends_on:
            - db
        ports:
            - "8069:8069"
        environment:
            - HOST=db
            - USER=admin
            - PASSWORD=admin
        volumes:
            - ./custom_addons:/mnt/extra-addons
            - ./odoo.conf:/etc/odoo/odoo.conf

volumes:
    odoo-db:
